params:
  workers: 0
  gpus: '-1'
  score_thresh: 0.1
  nms_thresh: 0.5
  lr: 0.00001
  epochs: 15

paths:
  input_image: ${hydra:runtime.cwd}/DATA/rgb_12_pxl/sample.tif
  mosaic_output: ${hydra:runtime.cwd}/DATA/rgb_12_pxl/mosaic
  labels: ${hydra:runtime.cwd}/DATA/rgb_12_pxl/train/labels
  train_file_name: ${hydra:runtime.cwd}/DATA/rgb_12_pxl/train/train.csv
  test_file_name: ${hydra:runtime.cwd}/temporal/crop

preprocessing:
  rows: 2
  columns: 2